export type CountryDialOption = {
  iso: string;
  name: string;
  /** ITU international prefix digits only (no leading +). */
  dial: string;
  /** Lowercase: name, dial, iso — used by the phone country search box. */
  search: string;
};

/** Country calling options from REST Countries (root + suffix per territory). NANP (+1) collapsed to a single dial digit per country. */
export const COUNTRY_DIAL_OPTIONS: CountryDialOption[] = [
  { iso: "AF", name: "Afghanistan", dial: "93", search: "afghanistan +93 af" },
  { iso: "AX", name: "Åland Islands", dial: "35818", search: "åland islands +35818 ax" },
  { iso: "AL", name: "Albania", dial: "355", search: "albania +355 al" },
  { iso: "DZ", name: "Algeria", dial: "213", search: "algeria +213 dz" },
  { iso: "AS", name: "American Samoa", dial: "1", search: "american samoa +1 as" },
  { iso: "AD", name: "Andorra", dial: "376", search: "andorra +376 ad" },
  { iso: "AO", name: "Angola", dial: "244", search: "angola +244 ao" },
  { iso: "AI", name: "Anguilla", dial: "1", search: "anguilla +1 ai" },
  { iso: "AG", name: "Antigua and Barbuda", dial: "1", search: "antigua and barbuda +1 ag" },
  { iso: "AR", name: "Argentina", dial: "54", search: "argentina +54 ar" },
  { iso: "AM", name: "Armenia", dial: "374", search: "armenia +374 am" },
  { iso: "AW", name: "Aruba", dial: "297", search: "aruba +297 aw" },
  { iso: "AU", name: "Australia", dial: "61", search: "australia +61 au" },
  { iso: "AT", name: "Austria", dial: "43", search: "austria +43 at" },
  { iso: "AZ", name: "Azerbaijan", dial: "994", search: "azerbaijan +994 az" },
  { iso: "BS", name: "Bahamas", dial: "1", search: "bahamas +1 bs" },
  { iso: "BH", name: "Bahrain", dial: "973", search: "bahrain +973 bh" },
  { iso: "BD", name: "Bangladesh", dial: "880", search: "bangladesh +880 bd" },
  { iso: "BB", name: "Barbados", dial: "1", search: "barbados +1 bb" },
  { iso: "BY", name: "Belarus", dial: "375", search: "belarus +375 by" },
  { iso: "BE", name: "Belgium", dial: "32", search: "belgium +32 be" },
  { iso: "BZ", name: "Belize", dial: "501", search: "belize +501 bz" },
  { iso: "BJ", name: "Benin", dial: "229", search: "benin +229 bj" },
  { iso: "BM", name: "Bermuda", dial: "1", search: "bermuda +1 bm" },
  { iso: "BT", name: "Bhutan", dial: "975", search: "bhutan +975 bt" },
  { iso: "BO", name: "Bolivia", dial: "591", search: "bolivia +591 bo" },
  { iso: "BA", name: "Bosnia and Herzegovina", dial: "387", search: "bosnia and herzegovina +387 ba" },
  { iso: "BW", name: "Botswana", dial: "267", search: "botswana +267 bw" },
  { iso: "BV", name: "Bouvet Island", dial: "47", search: "bouvet island +47 bv" },
  { iso: "BR", name: "Brazil", dial: "55", search: "brazil +55 br" },
  { iso: "IO", name: "British Indian Ocean Territory", dial: "246", search: "british indian ocean territory +246 io" },
  { iso: "VG", name: "British Virgin Islands", dial: "1", search: "british virgin islands +1 vg" },
  { iso: "BN", name: "Brunei", dial: "673", search: "brunei +673 bn" },
  { iso: "BG", name: "Bulgaria", dial: "359", search: "bulgaria +359 bg" },
  { iso: "BF", name: "Burkina Faso", dial: "226", search: "burkina faso +226 bf" },
  { iso: "BI", name: "Burundi", dial: "257", search: "burundi +257 bi" },
  { iso: "KH", name: "Cambodia", dial: "855", search: "cambodia +855 kh" },
  { iso: "CM", name: "Cameroon", dial: "237", search: "cameroon +237 cm" },
  { iso: "CA", name: "Canada", dial: "1", search: "canada +1 ca" },
  { iso: "CV", name: "Cape Verde", dial: "238", search: "cape verde +238 cv" },
  { iso: "BQ", name: "Caribbean Netherlands", dial: "599", search: "caribbean netherlands +599 bq" },
  { iso: "KY", name: "Cayman Islands", dial: "1", search: "cayman islands +1 ky" },
  { iso: "CF", name: "Central African Republic", dial: "236", search: "central african republic +236 cf" },
  { iso: "TD", name: "Chad", dial: "235", search: "chad +235 td" },
  { iso: "CL", name: "Chile", dial: "56", search: "chile +56 cl" },
  { iso: "CN", name: "China", dial: "86", search: "china +86 cn" },
  { iso: "CX", name: "Christmas Island", dial: "61", search: "christmas island +61 cx" },
  { iso: "CC", name: "Cocos (Keeling) Islands", dial: "61", search: "cocos (keeling) islands +61 cc" },
  { iso: "CO", name: "Colombia", dial: "57", search: "colombia +57 co" },
  { iso: "KM", name: "Comoros", dial: "269", search: "comoros +269 km" },
  { iso: "CK", name: "Cook Islands", dial: "682", search: "cook islands +682 ck" },
  { iso: "CR", name: "Costa Rica", dial: "506", search: "costa rica +506 cr" },
  { iso: "HR", name: "Croatia", dial: "385", search: "croatia +385 hr" },
  { iso: "CU", name: "Cuba", dial: "53", search: "cuba +53 cu" },
  { iso: "CW", name: "Curaçao", dial: "599", search: "curaçao +599 cw" },
  { iso: "CY", name: "Cyprus", dial: "357", search: "cyprus +357 cy" },
  { iso: "CZ", name: "Czechia", dial: "420", search: "czechia +420 cz" },
  { iso: "DK", name: "Denmark", dial: "45", search: "denmark +45 dk" },
  { iso: "DJ", name: "Djibouti", dial: "253", search: "djibouti +253 dj" },
  { iso: "DM", name: "Dominica", dial: "1", search: "dominica +1 dm" },
  { iso: "DO", name: "Dominican Republic", dial: "1", search: "dominican republic +1 do" },
  { iso: "CD", name: "DR Congo", dial: "243", search: "dr congo +243 cd" },
  { iso: "EC", name: "Ecuador", dial: "593", search: "ecuador +593 ec" },
  { iso: "EG", name: "Egypt", dial: "20", search: "egypt +20 eg" },
  { iso: "SV", name: "El Salvador", dial: "503", search: "el salvador +503 sv" },
  { iso: "GQ", name: "Equatorial Guinea", dial: "240", search: "equatorial guinea +240 gq" },
  { iso: "ER", name: "Eritrea", dial: "291", search: "eritrea +291 er" },
  { iso: "EE", name: "Estonia", dial: "372", search: "estonia +372 ee" },
  { iso: "SZ", name: "Eswatini", dial: "268", search: "eswatini +268 sz" },
  { iso: "ET", name: "Ethiopia", dial: "251", search: "ethiopia +251 et" },
  { iso: "FK", name: "Falkland Islands", dial: "500", search: "falkland islands +500 fk" },
  { iso: "FO", name: "Faroe Islands", dial: "298", search: "faroe islands +298 fo" },
  { iso: "FJ", name: "Fiji", dial: "679", search: "fiji +679 fj" },
  { iso: "FI", name: "Finland", dial: "358", search: "finland +358 fi" },
  { iso: "FR", name: "France", dial: "33", search: "france +33 fr" },
  { iso: "GF", name: "French Guiana", dial: "594", search: "french guiana +594 gf" },
  { iso: "PF", name: "French Polynesia", dial: "689", search: "french polynesia +689 pf" },
  { iso: "TF", name: "French Southern and Antarctic Lands", dial: "262", search: "french southern and antarctic lands +262 tf" },
  { iso: "GA", name: "Gabon", dial: "241", search: "gabon +241 ga" },
  { iso: "GM", name: "Gambia", dial: "220", search: "gambia +220 gm" },
  { iso: "GE", name: "Georgia", dial: "995", search: "georgia +995 ge" },
  { iso: "DE", name: "Germany", dial: "49", search: "germany +49 de" },
  { iso: "GH", name: "Ghana", dial: "233", search: "ghana +233 gh" },
  { iso: "GI", name: "Gibraltar", dial: "350", search: "gibraltar +350 gi" },
  { iso: "GR", name: "Greece", dial: "30", search: "greece +30 gr" },
  { iso: "GL", name: "Greenland", dial: "299", search: "greenland +299 gl" },
  { iso: "GD", name: "Grenada", dial: "1", search: "grenada +1 gd" },
  { iso: "GP", name: "Guadeloupe", dial: "590", search: "guadeloupe +590 gp" },
  { iso: "GU", name: "Guam", dial: "1", search: "guam +1 gu" },
  { iso: "GT", name: "Guatemala", dial: "502", search: "guatemala +502 gt" },
  { iso: "GG", name: "Guernsey", dial: "44", search: "guernsey +44 gg" },
  { iso: "GN", name: "Guinea", dial: "224", search: "guinea +224 gn" },
  { iso: "GW", name: "Guinea-Bissau", dial: "245", search: "guinea-bissau +245 gw" },
  { iso: "GY", name: "Guyana", dial: "592", search: "guyana +592 gy" },
  { iso: "HT", name: "Haiti", dial: "509", search: "haiti +509 ht" },
  { iso: "HN", name: "Honduras", dial: "504", search: "honduras +504 hn" },
  { iso: "HK", name: "Hong Kong", dial: "852", search: "hong kong +852 hk" },
  { iso: "HU", name: "Hungary", dial: "36", search: "hungary +36 hu" },
  { iso: "IS", name: "Iceland", dial: "354", search: "iceland +354 is" },
  { iso: "IN", name: "India", dial: "91", search: "india +91 in" },
  { iso: "ID", name: "Indonesia", dial: "62", search: "indonesia +62 id" },
  { iso: "IR", name: "Iran", dial: "98", search: "iran +98 ir" },
  { iso: "IQ", name: "Iraq", dial: "964", search: "iraq +964 iq" },
  { iso: "IE", name: "Ireland", dial: "353", search: "ireland +353 ie" },
  { iso: "IM", name: "Isle of Man", dial: "44", search: "isle of man +44 im" },
  { iso: "IL", name: "Israel", dial: "972", search: "israel +972 il" },
  { iso: "IT", name: "Italy", dial: "39", search: "italy +39 it" },
  { iso: "CI", name: "Ivory Coast", dial: "225", search: "ivory coast +225 ci" },
  { iso: "JM", name: "Jamaica", dial: "1", search: "jamaica +1 jm" },
  { iso: "JP", name: "Japan", dial: "81", search: "japan +81 jp" },
  { iso: "JE", name: "Jersey", dial: "44", search: "jersey +44 je" },
  { iso: "JO", name: "Jordan", dial: "962", search: "jordan +962 jo" },
  { iso: "KZ", name: "Kazakhstan", dial: "76", search: "kazakhstan +76 kz" },
  { iso: "KZ", name: "Kazakhstan", dial: "77", search: "kazakhstan +77 kz" },
  { iso: "KE", name: "Kenya", dial: "254", search: "kenya +254 ke" },
  { iso: "KI", name: "Kiribati", dial: "686", search: "kiribati +686 ki" },
  { iso: "XK", name: "Kosovo", dial: "383", search: "kosovo +383 xk" },
  { iso: "KW", name: "Kuwait", dial: "965", search: "kuwait +965 kw" },
  { iso: "KG", name: "Kyrgyzstan", dial: "996", search: "kyrgyzstan +996 kg" },
  { iso: "LA", name: "Laos", dial: "856", search: "laos +856 la" },
  { iso: "LV", name: "Latvia", dial: "371", search: "latvia +371 lv" },
  { iso: "LB", name: "Lebanon", dial: "961", search: "lebanon +961 lb" },
  { iso: "LS", name: "Lesotho", dial: "266", search: "lesotho +266 ls" },
  { iso: "LR", name: "Liberia", dial: "231", search: "liberia +231 lr" },
  { iso: "LY", name: "Libya", dial: "218", search: "libya +218 ly" },
  { iso: "LI", name: "Liechtenstein", dial: "423", search: "liechtenstein +423 li" },
  { iso: "LT", name: "Lithuania", dial: "370", search: "lithuania +370 lt" },
  { iso: "LU", name: "Luxembourg", dial: "352", search: "luxembourg +352 lu" },
  { iso: "MO", name: "Macau", dial: "853", search: "macau +853 mo" },
  { iso: "MG", name: "Madagascar", dial: "261", search: "madagascar +261 mg" },
  { iso: "MW", name: "Malawi", dial: "265", search: "malawi +265 mw" },
  { iso: "MY", name: "Malaysia", dial: "60", search: "malaysia +60 my" },
  { iso: "MV", name: "Maldives", dial: "960", search: "maldives +960 mv" },
  { iso: "ML", name: "Mali", dial: "223", search: "mali +223 ml" },
  { iso: "MT", name: "Malta", dial: "356", search: "malta +356 mt" },
  { iso: "MH", name: "Marshall Islands", dial: "692", search: "marshall islands +692 mh" },
  { iso: "MQ", name: "Martinique", dial: "596", search: "martinique +596 mq" },
  { iso: "MR", name: "Mauritania", dial: "222", search: "mauritania +222 mr" },
  { iso: "MU", name: "Mauritius", dial: "230", search: "mauritius +230 mu" },
  { iso: "YT", name: "Mayotte", dial: "262", search: "mayotte +262 yt" },
  { iso: "MX", name: "Mexico", dial: "52", search: "mexico +52 mx" },
  { iso: "FM", name: "Micronesia", dial: "691", search: "micronesia +691 fm" },
  { iso: "MD", name: "Moldova", dial: "373", search: "moldova +373 md" },
  { iso: "MC", name: "Monaco", dial: "377", search: "monaco +377 mc" },
  { iso: "MN", name: "Mongolia", dial: "976", search: "mongolia +976 mn" },
  { iso: "ME", name: "Montenegro", dial: "382", search: "montenegro +382 me" },
  { iso: "MS", name: "Montserrat", dial: "1", search: "montserrat +1 ms" },
  { iso: "MA", name: "Morocco", dial: "212", search: "morocco +212 ma" },
  { iso: "MZ", name: "Mozambique", dial: "258", search: "mozambique +258 mz" },
  { iso: "MM", name: "Myanmar", dial: "95", search: "myanmar +95 mm" },
  { iso: "NA", name: "Namibia", dial: "264", search: "namibia +264 na" },
  { iso: "NR", name: "Nauru", dial: "674", search: "nauru +674 nr" },
  { iso: "NP", name: "Nepal", dial: "977", search: "nepal +977 np" },
  { iso: "NL", name: "Netherlands", dial: "31", search: "netherlands +31 nl" },
  { iso: "NC", name: "New Caledonia", dial: "687", search: "new caledonia +687 nc" },
  { iso: "NZ", name: "New Zealand", dial: "64", search: "new zealand +64 nz" },
  { iso: "NI", name: "Nicaragua", dial: "505", search: "nicaragua +505 ni" },
  { iso: "NE", name: "Niger", dial: "227", search: "niger +227 ne" },
  { iso: "NG", name: "Nigeria", dial: "234", search: "nigeria +234 ng" },
  { iso: "NU", name: "Niue", dial: "683", search: "niue +683 nu" },
  { iso: "NF", name: "Norfolk Island", dial: "672", search: "norfolk island +672 nf" },
  { iso: "KP", name: "North Korea", dial: "850", search: "north korea +850 kp" },
  { iso: "MK", name: "North Macedonia", dial: "389", search: "north macedonia +389 mk" },
  { iso: "MP", name: "Northern Mariana Islands", dial: "1", search: "northern mariana islands +1 mp" },
  { iso: "NO", name: "Norway", dial: "47", search: "norway +47 no" },
  { iso: "OM", name: "Oman", dial: "968", search: "oman +968 om" },
  { iso: "PK", name: "Pakistan", dial: "92", search: "pakistan +92 pk" },
  { iso: "PW", name: "Palau", dial: "680", search: "palau +680 pw" },
  { iso: "PS", name: "Palestine", dial: "970", search: "palestine +970 ps" },
  { iso: "PA", name: "Panama", dial: "507", search: "panama +507 pa" },
  { iso: "PG", name: "Papua New Guinea", dial: "675", search: "papua new guinea +675 pg" },
  { iso: "PY", name: "Paraguay", dial: "595", search: "paraguay +595 py" },
  { iso: "PE", name: "Peru", dial: "51", search: "peru +51 pe" },
  { iso: "PH", name: "Philippines", dial: "63", search: "philippines +63 ph" },
  { iso: "PN", name: "Pitcairn Islands", dial: "64", search: "pitcairn islands +64 pn" },
  { iso: "PL", name: "Poland", dial: "48", search: "poland +48 pl" },
  { iso: "PT", name: "Portugal", dial: "351", search: "portugal +351 pt" },
  { iso: "PR", name: "Puerto Rico", dial: "1", search: "puerto rico +1 pr" },
  { iso: "QA", name: "Qatar", dial: "974", search: "qatar +974 qa" },
  { iso: "CG", name: "Republic of the Congo", dial: "242", search: "republic of the congo +242 cg" },
  { iso: "RE", name: "Réunion", dial: "262", search: "réunion +262 re" },
  { iso: "RO", name: "Romania", dial: "40", search: "romania +40 ro" },
  { iso: "RU", name: "Russia", dial: "73", search: "russia +73 ru" },
  { iso: "RU", name: "Russia", dial: "74", search: "russia +74 ru" },
  { iso: "RU", name: "Russia", dial: "75", search: "russia +75 ru" },
  { iso: "RU", name: "Russia", dial: "78", search: "russia +78 ru" },
  { iso: "RU", name: "Russia", dial: "79", search: "russia +79 ru" },
  { iso: "RW", name: "Rwanda", dial: "250", search: "rwanda +250 rw" },
  { iso: "BL", name: "Saint Barthélemy", dial: "590", search: "saint barthélemy +590 bl" },
  { iso: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", dial: "247", search: "saint helena, ascension and tristan da cunha +247 sh" },
  { iso: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", dial: "290", search: "saint helena, ascension and tristan da cunha +290 sh" },
  { iso: "KN", name: "Saint Kitts and Nevis", dial: "1", search: "saint kitts and nevis +1 kn" },
  { iso: "LC", name: "Saint Lucia", dial: "1", search: "saint lucia +1 lc" },
  { iso: "MF", name: "Saint Martin", dial: "590", search: "saint martin +590 mf" },
  { iso: "PM", name: "Saint Pierre and Miquelon", dial: "508", search: "saint pierre and miquelon +508 pm" },
  { iso: "VC", name: "Saint Vincent and the Grenadines", dial: "1", search: "saint vincent and the grenadines +1 vc" },
  { iso: "WS", name: "Samoa", dial: "685", search: "samoa +685 ws" },
  { iso: "SM", name: "San Marino", dial: "378", search: "san marino +378 sm" },
  { iso: "ST", name: "São Tomé and Príncipe", dial: "239", search: "são tomé and príncipe +239 st" },
  { iso: "SA", name: "Saudi Arabia", dial: "966", search: "saudi arabia +966 sa" },
  { iso: "SN", name: "Senegal", dial: "221", search: "senegal +221 sn" },
  { iso: "RS", name: "Serbia", dial: "381", search: "serbia +381 rs" },
  { iso: "SC", name: "Seychelles", dial: "248", search: "seychelles +248 sc" },
  { iso: "SL", name: "Sierra Leone", dial: "232", search: "sierra leone +232 sl" },
  { iso: "SG", name: "Singapore", dial: "65", search: "singapore +65 sg" },
  { iso: "SX", name: "Sint Maarten", dial: "1", search: "sint maarten +1 sx" },
  { iso: "SK", name: "Slovakia", dial: "421", search: "slovakia +421 sk" },
  { iso: "SI", name: "Slovenia", dial: "386", search: "slovenia +386 si" },
  { iso: "SB", name: "Solomon Islands", dial: "677", search: "solomon islands +677 sb" },
  { iso: "SO", name: "Somalia", dial: "252", search: "somalia +252 so" },
  { iso: "ZA", name: "South Africa", dial: "27", search: "south africa +27 za" },
  { iso: "GS", name: "South Georgia", dial: "500", search: "south georgia +500 gs" },
  { iso: "KR", name: "South Korea", dial: "82", search: "south korea +82 kr" },
  { iso: "SS", name: "South Sudan", dial: "211", search: "south sudan +211 ss" },
  { iso: "ES", name: "Spain", dial: "34", search: "spain +34 es" },
  { iso: "LK", name: "Sri Lanka", dial: "94", search: "sri lanka +94 lk" },
  { iso: "SD", name: "Sudan", dial: "249", search: "sudan +249 sd" },
  { iso: "SR", name: "Suriname", dial: "597", search: "suriname +597 sr" },
  { iso: "SJ", name: "Svalbard and Jan Mayen", dial: "4779", search: "svalbard and jan mayen +4779 sj" },
  { iso: "SE", name: "Sweden", dial: "46", search: "sweden +46 se" },
  { iso: "CH", name: "Switzerland", dial: "41", search: "switzerland +41 ch" },
  { iso: "SY", name: "Syria", dial: "963", search: "syria +963 sy" },
  { iso: "TW", name: "Taiwan", dial: "886", search: "taiwan +886 tw" },
  { iso: "TJ", name: "Tajikistan", dial: "992", search: "tajikistan +992 tj" },
  { iso: "TZ", name: "Tanzania", dial: "255", search: "tanzania +255 tz" },
  { iso: "TH", name: "Thailand", dial: "66", search: "thailand +66 th" },
  { iso: "TL", name: "Timor-Leste", dial: "670", search: "timor-leste +670 tl" },
  { iso: "TG", name: "Togo", dial: "228", search: "togo +228 tg" },
  { iso: "TK", name: "Tokelau", dial: "690", search: "tokelau +690 tk" },
  { iso: "TO", name: "Tonga", dial: "676", search: "tonga +676 to" },
  { iso: "TT", name: "Trinidad and Tobago", dial: "1", search: "trinidad and tobago +1 tt" },
  { iso: "TN", name: "Tunisia", dial: "216", search: "tunisia +216 tn" },
  { iso: "TR", name: "Turkey", dial: "90", search: "turkey +90 tr" },
  { iso: "TM", name: "Turkmenistan", dial: "993", search: "turkmenistan +993 tm" },
  { iso: "TC", name: "Turks and Caicos Islands", dial: "1", search: "turks and caicos islands +1 tc" },
  { iso: "TV", name: "Tuvalu", dial: "688", search: "tuvalu +688 tv" },
  { iso: "UG", name: "Uganda", dial: "256", search: "uganda +256 ug" },
  { iso: "UA", name: "Ukraine", dial: "380", search: "ukraine +380 ua" },
  { iso: "AE", name: "United Arab Emirates", dial: "971", search: "united arab emirates +971 ae" },
  { iso: "GB", name: "United Kingdom", dial: "44", search: "united kingdom +44 gb" },
  { iso: "US", name: "United States", dial: "1", search: "united states +1 us" },
  { iso: "UM", name: "United States Minor Outlying Islands", dial: "268", search: "united states minor outlying islands +268 um" },
  { iso: "VI", name: "United States Virgin Islands", dial: "1", search: "united states virgin islands +1 vi" },
  { iso: "UY", name: "Uruguay", dial: "598", search: "uruguay +598 uy" },
  { iso: "UZ", name: "Uzbekistan", dial: "998", search: "uzbekistan +998 uz" },
  { iso: "VU", name: "Vanuatu", dial: "678", search: "vanuatu +678 vu" },
  { iso: "VA", name: "Vatican City", dial: "379", search: "vatican city +379 va" },
  { iso: "VA", name: "Vatican City", dial: "3906698", search: "vatican city +3906698 va" },
  { iso: "VE", name: "Venezuela", dial: "58", search: "venezuela +58 ve" },
  { iso: "VN", name: "Vietnam", dial: "84", search: "vietnam +84 vn" },
  { iso: "WF", name: "Wallis and Futuna", dial: "681", search: "wallis and futuna +681 wf" },
  { iso: "EH", name: "Western Sahara", dial: "2125288", search: "western sahara +2125288 eh" },
  { iso: "EH", name: "Western Sahara", dial: "2125289", search: "western sahara +2125289 eh" },
  { iso: "YE", name: "Yemen", dial: "967", search: "yemen +967 ye" },
  { iso: "ZM", name: "Zambia", dial: "260", search: "zambia +260 zm" },
  { iso: "ZW", name: "Zimbabwe", dial: "263", search: "zimbabwe +263 zw" },
];
export function countryOptionKey(option: CountryDialOption): string {
  return `${option.iso}:${option.dial}`;
}

export function flagEmoji(iso: string): string {
  const code = iso.toUpperCase();
  if (code.length !== 2) return '🏳️';
  return String.fromCodePoint(
    ...[...code].map((char) => 0x1f1e6 - 65 + char.charCodeAt(0)),
  );
}

export const DEFAULT_COUNTRY_ISO = 'IN';
export const DEFAULT_COUNTRY_DIAL = '91';

export function getDefaultCountryOption(): CountryDialOption {
  return (
    COUNTRY_DIAL_OPTIONS.find(
      (o) => o.iso === DEFAULT_COUNTRY_ISO && o.dial === DEFAULT_COUNTRY_DIAL,
    ) ?? COUNTRY_DIAL_OPTIONS[0]
  );
}
